/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes.$slug'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/programmes/$slug',
  path: '/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoriesRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/our-work': typeof OurWorkRoute
  '/stories': typeof StoriesRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/our-work': typeof OurWorkRoute
  '/transparency': typeof TransparencyRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/get-involved': typeof GetInvolvedRoute
  '/impact': typeof ImpactRoute
  '/our-work': typeof OurWorkRoute
  '/stories': typeof StoriesRouteWithChildren
  '/transparency': typeof TransparencyRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/impact'
    | '/our-work'
    | '/stories'
    | '/transparency'
    | '/programmes/$slug'
    | '/stories/$slug'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/impact'
    | '/our-work'
    | '/transparency'
    | '/programmes/$slug'
    | '/stories/$slug'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/donate'
    | '/get-involved'
    | '/impact'
    | '/our-work'
    | '/stories'
    | '/transparency'
    | '/programmes/$slug'
    | '/stories/$slug'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  ImpactRoute: typeof ImpactRoute
  OurWorkRoute: typeof OurWorkRoute
  StoriesRoute: typeof StoriesRouteWithChildren
  TransparencyRoute: typeof TransparencyRoute
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/programmes/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
  }
}

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  ImpactRoute: ImpactRoute,
  OurWorkRoute: OurWorkRoute,
  StoriesRoute: StoriesRouteWithChildren,
  TransparencyRoute: TransparencyRoute,
  ProgrammesSlugRoute: ProgrammesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
